inherit_from: .rubocop_todo.yml

inherit_gem:
  percy-style:
    - default.yml

inherit_mode:
  merge:
    - Include

RSpec/DescribeClass:
  Exclude:
    - spec/percy/logger_spec.rb

# TODO: disable new cops
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - spec/support/redis_mock.rb
