inherit_gem:
  percy-style:
    - default.yml

inherit_mode:
  merge:
    - Include

RSpec/DescribeClass:
  Exclude:
    - spec/percy/logger_spec.rb

AllCops:
  Exclude:
    - spec/support/redis_mock.rb
