version: 2.1

jobs:
  ruby_25:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    steps:
      - checkout
      - run: gem update --system
      - run: bundle install
      - run: bundle exec rubocop -D

workflows:
  version: 2
  test:
    jobs:
      - ruby_25
