agents: &agents
  os: 'linux_small'

command: &command
  - make test

steps:
  - label: ':rubocop: Lint'
    agents: *agents
    command:
      - make lint

  - label: ':rspec: Test Ruby 3.0'
    env:
      BASE_IMAGE: 'ruby:3.0-alpine'
    agents: *agents
    command: *command

  - label: ':rspec: Test Ruby 3.2'
    env:
      BASE_IMAGE: 'ruby:3.2-alpine'
    agents: *agents
    command: *command

  - label: ':rspec: Test Ruby 3.3'
    env:
      BASE_IMAGE: 'ruby:3.3-alpine'
    agents: *agents
    command: *command
